### ISSUE TITLE
Booting baremetalhost on baremetal node gets stuck.

### ISSUE THREAD

**Issue by achuzhoy** [openshift-metal3/dev-scripts#418]
Booting baremetalhost on baremetal node gets stuck.

Environment:
https://github.com/metalkube/dev-scripts.git
commit 4cac06f8d70786d8b4edf82e886215595fd23195
Cluster version is 4.0.0-0.ci-2019-04-17-133604

Steps to reproduce:

Successfully run:

        ./01_install_requirements.sh
        ./02_configure_host.sh
        ./03_ocp_repo_sync.sh
        ./04_setup_ironic.sh
        ./05_build_ocp_installer.sh
        ./06_create_cluster.sh
        ./08_deploy_bmo.sh

[stack@rhos-compute-node-14 dev-scripts]$ oc get clusterversion
NAME      VERSION                        AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.0.0-0.ci-2019-04-17-133604   True        False         3d9h    Cluster version is 4.0.0-0.ci-2019-04-17-133604

[stack@rhos-compute-node-14 dev-scripts]$ oc get node
NAME       STATUS   ROLES    AGE     VERSION
master-0   Ready    master   3d10h   v1.13.4+d4ce02c1d
master-1   Ready    master   3d10h   v1.13.4+d4ce02c1d
master-2   Ready    master   3d10h   v1.13.4+d4ce02c1d

```
[stack@rhos-compute-node-14 dev-scripts]$ cat ~/worker.yaml 
---
apiVersion: v1
kind: Secret
metadata:
  name: sasha-secret
type: Opaque
data:
  username: <string>
  password: <string>
---
apiVersion: metalkube.org/v1alpha1
kind: BareMetalHost
metadata:
  name: sasha-worker2
  labels:
    metalkubedemo: ""
spec:
  online: true
  bmc:
    address: ipmi://<ip>:623
    credentialsName: sasha-secret
  bootMACAddress: 00:0a:f7:7f:24:88
  userData:
    namespace: openshift-machine-api
    name: worker-user-data
  image:
    url: "http://172.22.0.1/images/rhcos-ootpa-latest.qcow2"
    checksum: "http://172.22.0.1/images/rhcos-ootpa-latest.qcow2.md5sum"
```

run:
oc create -n openshift-machine-api -f ~/worker-0.yml

Result:
The node is added in ironic:
[stack@rhos-compute-node-14 dev-scripts]$ openstack baremetal node list|grep sasha-worker2
| 7878fcc4-a671-4aeb-a31d-735daac2f408 | sasha-worker2      | 7878fcc4-a671-4aeb-a31d-735daac2f408 | power on    | active             | False       |

[stack@rhos-compute-node-14 dev-scripts]$ oc get -n openshift-machine-api baremetalhost/sasha-worker2
NAME            STATUS   PROVISIONING STATUS   MACHINE           BMC                       HARDWARE PROFILE   ONLINE   ERROR
sasha-worker2   OK       provisioned           ostest-master-1   ipmi://<IP>:623   unknown            true    

But the node doesn't complete the boot. The console output is attached to the bz.
The issue reproduces.

The image is attached to the BZ here:
https://bugzilla.redhat.com/show_bug.cgi?id=1702362
