### ISSUE TITLE
worker on a BM node with several disk doesn't boot off the disk after the image was written.

### ISSUE THREAD

**Issue by achuzhoy** [openshift-metal3/dev-scripts#447]
worker on a BM node with several disk doesn't boot off the disk after the image was written.

Environment:

version   4.0.0-0.ci-2019-04-17-133604   True        False         3h32m   Cluster version is 4.0.0-0.ci-2019-04-17-133604 

git commit: 1dcf18675943db899ba41ce34eca07923f5ac2ae

Steps to reproduce:
1. Deploy rhhi on BM environment.
2. Add a worker that's a BM machine with several disks:

```
[root@rhos-compute-node-14 ~]# cat /home/stack/worker.yaml 
---
apiVersion: v1
kind: Secret
metadata:
  name: sasha-secret
type: Opaque
data:
  username: cm9vdA==
  password: Y2Fsdmlu
---
apiVersion: metalkube.org/v1alpha1
kind: BareMetalHost
metadata:
  name: worker-0
  labels:
    metalkubedemo: ""
spec:
  online: true
  bmc:
    address: ipmi://<ip>:623
    credentialsName: sasha-secret
  bootMACAddress: 00:0a:f7:7f:24:88
  userData:
    namespace: openshift-machine-api
    name: worker-user-data

```

Result:

[stack@rhos-compute-node-14 dev-scripts]$ openstack baremetal node list                                                                                                           
-------------------+-------------+--------------------+-------------+                             
| UUID                                 | Name               | Instance UUID                        | Power State | Provisioning State | Maintenance |                             
-------------------+-------------+--------------------+-------------+                             
| 3a166972-4ba4-4ead-8368-72a163d57451 | openshift-master-1 | None                                 | power on    | active             | False       |                             
| 96fc064b-fb72-4805-ad0c-7469b44f6614 | openshift-master-2 | None                                 | power on    | active             | False       |                             
| afea88b3-3dcc-4af5-93b4-b7539cc27512 | openshift-master-0 | None                                 | power on    | active             | False       |                             
| a23132fd-d4dd-4f5b-a71f-ca8b00c54a0a | worker-0           | a23132fd-d4dd-4f5b-a71f-ca8b00c54a0a | power on    | active             | False       |                             
+--------------------------------------+--------------------+-------------------

[stack@rhos-compute-node-14 dev-scripts]$ openstack baremetal node show worker-0 -f value -c properties
                 
{u'cpu_arch': u'x86_64', u'root_device': {u'name': u'/dev/sda'}, u'local_gb': 50}  

[stack@rhos-compute-node-14 dev-scripts]$ oc get node                                                                                                                             
NAME       STATUS   ROLES    AGE    VERSION                                                                                                                                       
master-0   Ready    master   4h2m   v1.13.4+d4ce02c1d                                                                                                                             
master-1   Ready    master   4h2m   v1.13.4+d4ce02c1d                                                                                                                             
master-2   Ready    master   4h2m   v1.13.4+d4ce02c1d   

[stack@rhos-compute-node-14 dev-scripts]$ oc get baremetalhost -n openshift-machine-api                                                                                           
NAME                 STATUS   PROVISIONING STATUS      MACHINE                 BMC                       HARDWARE PROFILE   ONLINE   ERROR                                        
openshift-master-0   OK       externally provisioned   ostest-master-0         ipmi://10.19.184.10                          true                                                  
openshift-master-1   OK       externally provisioned   ostest-master-1         ipmi://10.19.184.12                          true                                                  
openshift-master-2   OK       externally provisioned   ostest-master-2         ipmi://10.19.184.14                          true                                                  
worker-0             OK       provisioned              ostest-worker-0-mt425   ipmi://10.19.184.33:623   unknown            true   

The worker node itself boots the ipa image. If I block ports 67/69 on the provision host, then the worker node says "no boot device is available" after trying the pxe option. The bios is set to boot the HD first.

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1702818
