### ISSUE TITLE
After enabling FeatureGate/TechPreviewNoUpgrade nodes reboot and do not come online again

### ISSUE THREAD

**Issue by nixpanic** [openshift-metal3/dev-scripts#511]
**Describe the bug**
When I enable the FeatureGate/TechPreviewNoUpgrade the nodes reboot and any `oc` commands fail. It seems the API server does not come up again.

**To Reproduce**
```
# make CONFIG=config_...sh
...
# oc --config ocp/auth/kubeconfig apply -f - << EOF
apiVersion: config.openshift.io/v1
kind: FeatureGate
metadata:
  namespace: openshift-config
  name: cluster
spec: 
  featureSet: TechPreviewNoUpgrade
EOF
```

**Expected/observed behavior**
I'd like to try out the CSIBlockVolume feature that gets enabled with this change. In the commandline arguments of `hyperkube kube-scheduler` on some the nodes the FeatureGate does have the expected effect (contains `--feature-gates=CSIBlockVolume=true,...`). Not all nodes seem to have this set though...

**Additional context**
Initially I thought it to be related to issues where rebooting nodes cause the breakage. However not enabling the FeatureGate and rebooting the nodes does work without issues. So there really seems to be something wrong when enabling the FeatureGate.
